### ISSUE TITLE
进来获取永久可白嫖的公益机场

### ISSUE THREAD

**Issue by walkerdygm82** [ZGQ-inc/overthefirewall#24]
注册地址：https://kuailejc.xyz/#/register?code=Y9Iljz8X
全场7折优惠码： 7zyyds
公益白嫖码： kuailejc.xyz

**Comment by ZGQ-inc** [comment]
昨天刚开的机场，今天就开始到处打广告？这么急着盈利？你机场主难道不露个面解释一下为什么不通过正当渠道打广告吗？

**Comment by peasoft** [comment]
这种人就这样，我的项目下面也被打广告了，只能是发现了及时删掉还有去这个人的主页把他拉黑。

**Comment by walkerdygm82** [comment]
不知道不能打 不好意思哈 新开小白机场，对不起 请体量下
