### ISSUE TITLE
Windows端登录时sign in界面时间太长

### ISSUE THREAD

**Issue by SuenChi** [ZGQ-inc/overthefirewall#5]
这是正常现象吗？
还有我试了好几个注册码和邮箱，都expired了

**Comment by SuenChi** [comment]
> 这是正常现象吗？ 还有我试了好几

**Comment by ZGQ-inc** [comment]
是有些问题，更新了新的注册码，再试试看？
> **EU4O9RJ6TMIYBVYWFFI5CAY**
> 
> 邮箱：exxhc@mfk.app
> 
> 密码：sxfgA6sf

> **ECVS4PH3Z4QE7XONUDQWAHL**
> 
> 邮箱：dylanclarkso.n3.6.7.1.0.1.0@gmail.com
> 
> 密码：oE9uDveG

**Comment by SuenChi** [comment]
十分感谢！！！
