### ISSUE TITLE
网站打开不了

### ISSUE THREAD

**Issue by Badcomput** [ZGQ-inc/overthefirewall#8]
https://zgq-inc.github.io/overthefirewall/
是被ben了嘛

**Comment by ZGQ-inc** [comment]
近期开大会，GFW拉高了防御，Github pages的域名已被完全SNI阻断，大陆全部地区已被DNS污染无法访问，详情请查看https://t.me/ZGQincLiqun/2159

**Comment by ZGQ-inc** [comment]
还有是ban不是ben，话说你都翻墙上Github了为什么Github pages打不开？

**Comment by Badcomput** [comment]
好的哥
